---
- name: 
  hosts: k8s-all-r9:children
  become: true

  tasks:
  - name: Create k8s config, this will overwrite existing configs in /etc/yum.repos.d/kubernetes.repo
    yum_repository:
      name: kube
      description: Kubernetes repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      enabled: 1
      gpgcheck: 1
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    shell: |
            swapoff -a
            sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

  - name: Stopping and disabling firewalld
    service: 
      name: firewalld
      state: stopped
      enabled: false

################################################################################

- name: Installing and starting kubelet on master nodes (control planes)
  hosts: k8s-m-r9
  become: true
  # vars:
  #   node_ip: "192.168.0.50"

  tasks:
# https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
  - name: Install Kubernetes binaries with disable_excludes
    become: true
    ansible.builtin.yum: 
      name: "{{ item }}"
      state: present
      update_cache: yes
      disable_excludes: 'kubernetes'
    loop:
        - kubelet 
        - kubeadm 
        - kubectl

  # - name: Configure node ip
  #   lineinfile:
  #     path: /etc/default/kubelet
  #     line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Restart kubelet
    service:
      name: kubelet
      enabled: true
      daemon_reload: yes
      state: restarted

  - name: Enabling kubectl command for general user
    become: yes
    become_user: ansible
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755

  - name: copy admin.conf
    copy:
      remote_src: yes
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      owner: ansible

################################################################################

- name: Installing and starting kubelet on worker nodes
  hosts: k8s-w-r9
  become: true
  # vars:
  #   node_ip: "192.68.0.51" 

  tasks:
  - name: Install Kubernetes binaries with disable_excludes
    become: true
    ansible.builtin.yum: 
      name: "{{ item }}"
      state: present
      update_cache: yes
      disable_excludes: 'kubernetes'
    loop:
        - kubelet 
        - kubeadm 

  # - name: Configure node ip
  #   lineinfile:
  #     path: /etc/default/kubelet
  #     line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Restart kubelet
    service:
      name: kubelet
      enabled: true
      daemon_reload: yes
      state: restarted